version: '2'
services:
    arquivista-app:
        image: arquivista
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://arquivista-mysql:3306/arquivista?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 80:80
    arquivista-mysql:
        extends:
            file: mysql.yml
            service: arquivista-mysql
